language: node_js
node_js:
  - node
  - 14
  - 12
  - 10
cache:
  npm: false
  directories:
    - "~/.pnpm-store"

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install --frozen-lockfile
script:
  - pnpm recursive run dev:readonly
  - pnpm recursive run test
